### ISSUE TITLE
example of passing options?

### ISSUE THREAD

**Issue by jedierikb** [corneliusio/gulp-svgo#1]
Sorry, but it is not obvious to me how to pass options to svgo.  I tried:

`.pipe(svgo('--pretty'))`

and

`.pipe(svgo(['--pretty']))`

to no avail.  Thank you for your guidance.

**Comment by corneliusio** [comment]
Yeah, the documentation for SVGO's programmatic options is pretty non-existent. Since 99% of the time, the default config is good I haven't done anything to the way it works—but have just allowed for the options to be passed to the SVGO instance untouched for any more advanced users to take advantage of if they choose.

That said, the specific option you're wanting is passed like this.

``` js
.pipe(svgo({
    js2svg: {
        indent: 2, // optional, default is 4
        pretty: true
    }
}))
```

Pretty odd, but it's how they have it setup.
Had to just look through their code and examples to figure it out though.
https://github.com/svg/svgo

Hope that helps!

**Comment by jedierikb** [comment]
Thanks, got it now!

Some other pages which were helpful (for others who come this way):
http://stackoverflow.com/questions/28637984/svgo-add-plugin
https://github.com/imagemin/imagemin-svgo/issues/12
